homework 0, 1.1, 1.3
js-tasks-ru/jsbasic-20230116-2_ladyananda pull request #1
Opened 2023-01-22 19:57 UTC by LadyAnanda

2023-01-22 19:57 UTC, jsru commented
Спасибо за отправленный пулриквест, теперь @SinimaWath должен запустить тесты.

2023-01-23 15:59 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-01-23 16:00 UTC, SinimaWath requested changes
Тут все ок, надо решить все добавленные задачи

2023-01-24 11:19 UTC, SinimaWath approved these changes
все круто

2023-01-24 11:20 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-01-24 11:20 UTC, merged